# Generated by Django 4.1 on 2023-05-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
