# Generated by Django 4.1 on 2023-05-09 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticketApp", "0003_alter_ticket_date_created_alter_ticket_last_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="user",
            new_name="created_by",
        ),
    ]
