# Generated by Django 4.1 on 2023-05-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticketApp", "0005_reply"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reply",
            old_name="description",
            new_name="comment",
        ),
    ]
